name: Backend CI
on:
  push:
    branches: [main, dev]
    paths: ["backend/**", "infra/**"]
  pull_request:
    branches: [main, dev]
    paths: ["backend/**", "infra/**"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Lint placeholder
        run: |
          echo "TODO: add flake8 / pytest once backend is implemented."
